branch-defaults:
  main:
    environment: vthacks_frontend

environment-defaults:
  vthacks_frontend:
    branch: main
    repository: null

global:
  application_name: vthacks_frontend
  default_ec2_keyname: null
  default_platform: Node.js 18 running on 64bit Amazon Linux 2023
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: aws-elasticbeanstalk-ec2-role
  platform_name: null
  platform_version: null
  sc: git
  workspace_type: Application
