branch-defaults:
  main:
    environment: prod
  map:
    environment: prod
    group_suffix: null
environment-defaults:
  prod:
    branch: null
    repository: null
global:
  application_name: vthacks-frontend
  default_ec2_keyname: null
  default_platform: Node.js 18 running on 64bit Amazon Linux 2023
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: aws-elasticbeanstalk-ec2-role
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
